#
# Copyright (c) 2015, Real-Time Innovations, Inc. All rights reserved.
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#

libs-$(CONFIG_LIB_LWIP) += liblwip
liblwip: $(libc) common
